server:
  port: 80
  tomcat:
    connection-timeout: 60000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ruiji?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true  # 映射实体或者属性时将下划线去掉，并按驼峰命名法映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 日志
  global-config:
    db-config:
      id-type: assign_id
ruiji:
  images:
    path: C:\Users\XM\Desktop\images\